spring:
  datasource:
    driveClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_school
    username: user_school
    password: "@School2021"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
